# Generated by Django 2.2.1 on 2019-05-13 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0002_tweeteruser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweeter.TweeterUser'),
        ),
    ]
