# Generated by Django 2.2.1 on 2019-05-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0003_auto_20190513_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='username',
            new_name='author',
        ),
    ]
