# Generated by Django 2.2.1 on 2019-05-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0004_auto_20190513_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweeteruser',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, to='tweeter.TweeterUser'),
        ),
    ]
