# Generated by Django 2.2.1 on 2019-05-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0005_tweeteruser_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweeteruser',
            name='following',
            field=models.ManyToManyField(blank=True, to='tweeter.TweeterUser'),
        ),
    ]
